name: Build Docker image

on:
  push:
    branches-ignore:
      - master  # Covered by docker-push.yml
  pull_request:

jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: read  # To read NPM registry

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    with:
      image-tag: ghcr.io/gunet/wallet-frontend:latest
      docker-push: false
